# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x04\x46\x65\x64V\"\x99\x01\n\x08Resource\x1a\x1c\n\x03REQ\x12\x15\n\rnum_endpoints\x18\x01 \x01(\x05\x1a?\n\x03REP\x12%\n\x06status\x18\x01 \x01(\x0e\x32\x15.FedV.Resource.Status\x12\x11\n\tendpoints\x18\x02 \x03(\t\".\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\"]\n\x04Task\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x13\n\x0bweb_task_id\x18\x03 \x01(\t\x12\x11\n\ttask_type\x18\x04 \x01(\t\x12\x0c\n\x04task\x18\x05 \x01(\t\"\x94\x01\n\nTaskSubmit\x1a&\n\x03REQ\x12\x1f\n\x0btask_submit\x18\x01 \x01(\x0b\x32\n.FedV.Task\x1a.\n\x03REP\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.FedV.TaskSubmit.Status\".\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x32\x88\x01\n\tFedWorker\x12?\n\x13TaskResourceRequire\x12\x12.FedV.Resource.REQ\x1a\x12.FedV.Resource.REP\"\x00\x12:\n\nTaskSubmit\x12\x14.FedV.TaskSubmit.REQ\x1a\x14.FedV.TaskSubmit.REP\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESOURCE']._serialized_start=23
  _globals['_RESOURCE']._serialized_end=176
  _globals['_RESOURCE_REQ']._serialized_start=35
  _globals['_RESOURCE_REQ']._serialized_end=63
  _globals['_RESOURCE_REP']._serialized_start=65
  _globals['_RESOURCE_REP']._serialized_end=128
  _globals['_RESOURCE_STATUS']._serialized_start=130
  _globals['_RESOURCE_STATUS']._serialized_end=176
  _globals['_TASK']._serialized_start=178
  _globals['_TASK']._serialized_end=271
  _globals['_TASKSUBMIT']._serialized_start=274
  _globals['_TASKSUBMIT']._serialized_end=422
  _globals['_TASKSUBMIT_REQ']._serialized_start=288
  _globals['_TASKSUBMIT_REQ']._serialized_end=326
  _globals['_TASKSUBMIT_REP']._serialized_start=328
  _globals['_TASKSUBMIT_REP']._serialized_end=374
  _globals['_TASKSUBMIT_STATUS']._serialized_start=130
  _globals['_TASKSUBMIT_STATUS']._serialized_end=176
  _globals['_FEDWORKER']._serialized_start=425
  _globals['_FEDWORKER']._serialized_end=561
# @@protoc_insertion_point(module_scope)
