# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import worker_pb2 as worker__pb2


class FedWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TaskResourceRequire = channel.unary_unary(
                '/FedV.FedWorker/TaskResourceRequire',
                request_serializer=worker__pb2.Resource.REQ.SerializeToString,
                response_deserializer=worker__pb2.Resource.REP.FromString,
                )
        self.TaskSubmit = channel.unary_unary(
                '/FedV.FedWorker/TaskSubmit',
                request_serializer=worker__pb2.TaskSubmit.REQ.SerializeToString,
                response_deserializer=worker__pb2.TaskSubmit.REP.FromString,
                )


class FedWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TaskResourceRequire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskSubmit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FedWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TaskResourceRequire': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskResourceRequire,
                    request_deserializer=worker__pb2.Resource.REQ.FromString,
                    response_serializer=worker__pb2.Resource.REP.SerializeToString,
            ),
            'TaskSubmit': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskSubmit,
                    request_deserializer=worker__pb2.TaskSubmit.REQ.FromString,
                    response_serializer=worker__pb2.TaskSubmit.REP.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FedV.FedWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FedWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TaskResourceRequire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FedV.FedWorker/TaskResourceRequire',
            worker__pb2.Resource.REQ.SerializeToString,
            worker__pb2.Resource.REP.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TaskSubmit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FedV.FedWorker/TaskSubmit',
            worker__pb2.TaskSubmit.REQ.SerializeToString,
            worker__pb2.TaskSubmit.REP.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
